#!/bin/bash
# Reload a varnish config
# Author: Kristian Lyngstol <kristian@linpro.no>

FILE="/etc/varnish/default.vcl"

# Hostname and management port 
# (defined in /etc/default/varnish or on startup)
HOSTPORT="localhost:6082" 
NOW=`date +%s`

error()
{
	echo 1>&2 "Failed to reload $FILE."
	exit 1
}

varnishadm -T $HOSTPORT vcl.load reload$NOW $FILE || error
sleep 0.1
varnishadm -T $HOSTPORT vcl.use reload$NOW || error
sleep 0.1
echo Current configs:
varnishadm -T $HOSTPORT vcl.list
