name: ci

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-18.04

    strategy:
      matrix:
        compiler: [clang, gcc]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: apt-get
      run: sudo apt-get install -y libedit-dev lcov python3-docutils python3-sphinx
    - name: prereq
      run: |
        git clone -b varnish-6.6.2 https://github.com/varnishcache/varnish-cache.git
        cd varnish-cache && ./autogen.sh && ./configure && make && sudo make install && sudo ldconfig && cd ..
    - name: make check
      run: make check CFLAGS="-Wall -Wextra -Werror" VERBOSE=1
